apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: machine-learning-01-svc-dev
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/phelun/microservices.git'
    path: machine-learning-01-svc/overlays/dev
    targetRevision: main
    kustomize:
      namePrefix: dev-
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: dev-machine-learning-01-svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
