apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: webapp-response-time
spec:
  metrics:
    - name: response-time
      interval: 30s
      count: 3
      inconclusiveLimit: 3
      provider:
        prometheus:
          # address: http://prometheus-server.prometheus.svc.cluster.local
          address: http://prometheus-kube-prometheus-prometheus.monitoring.svc.cluster.local:9090
          # query: |
          #   avg(http_request_duration_seconds{app="webapp"})
          query: |
            scalar(avg(http_request_duration_seconds{app="webapp"}))
      successCondition: result < 0.5
      failureCondition: result >= 0.5
