apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp
  namespace: ceverything-argo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
        - name: webapp
          image: nginx
          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: webapp
  namespace: ceverything-argo
spec:
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: webapp
  type: ClusterIP

---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: webapp-monitor
  namespace: ceverything-argo
  labels:
    team: frontend
spec:
  selector:
    matchLabels:
      app: webapp
  endpoints:
    - port: web  