# apiVersion: argoproj.io/v1alpha1
# kind: Rollout
# metadata:
#   name: example-rollout
# spec:
#   replicas: 3
#   selector:
#     matchLabels:
#       app: example
#   template:
#     metadata:
#       labels:
#         app: example
#     spec:
#       containers:
#       - name: your-container
#         image: nginx:1.20
#   strategy:
#     canary:
#       steps:
#       - setWeight: 20
#       - pause: {duration: 10s}
######################### 02 DEMO #########################
# apiVersion: argoproj.io/v1alpha1
# kind: Rollout
# metadata:
#   name: canary-demo-app
# spec:
#   replicas: 4
#   strategy:
#     canary:
#       steps:
#       - setWeight: 25
#       - pause: {}
#       - setWeight: 50
#       - pause: {}
#       - setWeight: 75
#       - pause: {}
#   selector:
#     matchLabels:
#       app: demo-app
#   template:
#     metadata:
#       labels:
#         app: demo-app
#     spec:
#       containers:
#       - name: demo-container
#         image: nginx:1.20.0
#         ports:
#         - containerPort: 80
######################### 03 DEMO #########################
# apiVersion: argoproj.io/v1alpha1
# kind: Rollout
# metadata:
#   name: example-rollout
# spec:
#   replicas: 3
#   selector:
#     matchLabels:
#       app: example
#   template:
#     metadata:
#       labels:
#         app: example
#     spec:
#       containers:
#       - name: rollouts-demo
#         image: argoproj/rollouts-demo:blue
#         ports:
#         - containerPort: 8080
#   strategy:
#     canary:
#       steps:
#       - setWeight: 20
#       - pause: {duration: 10s}
#       - setWeight: 40
#       - pause: {duration: 10s}
#       - setWeight: 60
#       - pause: {duration: 10s}
#       - setWeight: 80
#       - pause: {}
######################### 04 DEMO #########################
# apiVersion: argoproj.io/v1alpha1
# kind: Rollout
# metadata:
#   name: webapp-rollout
# spec:
#   replicas: 2
#   selector:
#     matchLabels:
#       app: webapp
#   template:
#     metadata:
#       labels:
#         app: webapp
#     spec:
#       containers:
#         - name: webapp
#           image: nginx:1.19.0
#           ports:
#             - containerPort: 80
#   strategy:
#     canary:
#       steps:
#         - setWeight: 50
#         - pause: {duration: 10s}
#         - analysis:
#             templates:
#               - templateName: dev-webapp-response-time
#         - setWeight: 50
#         - pause: {}              
#         - setWeight: 100
######################## 05 MOCK ANALYSIS ####################
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: webapp-rollout
spec:
  replicas: 4
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
        - name: webapp
          image: nginx:1.19.10
          ports:
            - containerPort: 80
  strategy:
    canary:
      steps:
        - setWeight: 50
        - pause: {}
        - analysis:
            templates:
              - templateName: mock-success-rate-check
        - setWeight: 100