# apiVersion: argoproj.io/v1alpha1
# kind: Rollout
# metadata:
#   name: example-rollout
# spec:
#   replicas: 3
#   selector:
#     matchLabels:
#       app: example
#   template:
#     metadata:
#       labels:
#         app: example
#     spec:
#       containers:
#       - name: your-container
#         image: nginx:1.20
#   strategy:
#     canary:
#       steps:
#       - setWeight: 20
#       - pause: {duration: 10s}
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: canary-demo-app
spec:
  replicas: 4
  strategy:
    canary:
      steps:
      - setWeight: 25
      - pause: {}
      - setWeight: 50
      - pause: {}
      - setWeight: 75
      - pause: {}
  selector:
    matchLabels:
      app: demo-app
  template:
    metadata:
      labels:
        app: demo-app
    spec:
      containers:
      - name: demo-container
        image: nginx:1.19.0
        ports:
        - containerPort: 80