apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: example-rollout
spec:
  replicas: 3
  selector:
    matchLabels:
      app: example
  template:
    metadata:
      labels:
        app: example
    spec:
      containers:
      - name: your-container
        image: nginx:1.19
  strategy:
    canary:
      steps:
      - setWeight: 20
      - pause: {duration: 10s}
