apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
    name: redis-service
spec:
  selector:
    name: redis-pod
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379
  type: ClusterIP