apiVersion: v1
kind: Service
metadata:
  name: customer-product-rating-svc-service
  labels:
    app: customer-product-rating-svc
spec:
  selector:
    app: customer-product-rating-svc
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5000
  type: LoadBalancer

