apiVersion: v1
kind: Service
metadata:
  name: aws-workshop-webapp-svc
  annotations:
    nginx.ingress.kubernetes.io/healthcheck-path: "/"
  labels:
    env: dev
spec:
  selector:
    app: demo-frontend
