apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-frontend
  namespace: aws-workshop-webapp-svc
  labels:
    env: dev
spec:
  selector:
    matchLabels:
      app: demo-frontend
  template:
    metadata:
      labels:
        app: demo-frontend