# namePrefix: dev-

# commonLabels:
#   env: dev

# commonAnnotations:
#   note: amazon workshop testing web app 

# bases:
# - ../../base

# patchesStrategicMerge:
# - configmap.yaml
# - ingress.yaml

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: /amazon-eks-frontend-ci
  newName: /amazon-eks-frontend-ci
  newTag: a45dcea4
- name: 658951324167.dkr.ecr.eu-west-1.amazonaws.com/amazon-eks-frontend-ci
  newName: 658951324167.dkr.ecr.eu-west-1.amazonaws.com/amazon-eks-frontend-ci
  newTag: d1dc2db4
resources:
- ../../base
patchesStrategicMerge:
- amazon-eks-frontend-deployment-patch.yaml
- amazon-eks-frontend-svc-patch.yaml
