apiVersion: v1
kind: Service
metadata:
  name: db
  labels:
    name: db-service
spec:
  selector:
    name: postgres-pod
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  type: ClusterIP